#!/usr/bin/env python
# vi: ft=python
import sys

from org.cmyers.example import app

def main():
    a = app.App()
    print "Developers: "
    for d in a.developers():
        print "\t" + d

if __name__ == '__main__':
    sys.exit(main())

