#!/bin/bash

set -e

if [[ -z "$QBT_ENV_PYTHON" ]]; then
    echo "This package requires the variable QBT_ENV_PYTHON be set to e.g. '2_7', '3_2', etc" 1>&2
    exit 1
fi

eval export PYTHON_BIN=\$PYTHON_${QBT_ENV_PYTHON}_BIN
if [[ ! -x "$PYTHON_BIN" ]]; then
    echo "This package requires the variable PYTHON_${QBT_ENV_PYTHON}_BIN be set to the path to a python binary matching that version" 1>&2
    exit 1
fi

# If your virtualenv is very large, you may wish to put it elsewhere
VE=$OUTPUT_REPORTS_DIR/ve

$PYTHON_BIN -m virtualenv $VE

source $VE/bin/activate

# install wheel first if present
if [[ -f $INPUT_ARTIFACTS_DIR/weak/pypi.wheel/strong/pypi.wheel/python-src/wheel.tar.gz ]]; then
    pip install $INPUT_ARTIFACTS_DIR/weak/pypi.wheel/strong/pypi.wheel/python-src/wheel.tar.gz
fi

# install all strong python dependencies
for type in src egg whl; do
    ext=$type
    if [[ "$ext" == "src" ]]; then
        ext="tar.gz"
    fi
    for file in $INPUT_ARTIFACTS_DIR/strong/*/python-$type/*.$ext; do
        if [[ -f $file ]]; then
            pip install $file
        fi
    done
done

for i in $(find . -type f -name 'test*.py'); do
    OUTPUT=$OUTPUT_REPORTS_DIR/test-results/$i.txt
    mkdir -p $(dirname $OUTPUT)
    python $i 2>&1 | tee $OUTPUT_REPORTS_DIR/test-results/$i.txt
done

# TODO: switch to unit2 discover -v
# TODO: copy other test results into reports dir

