#!/bin/bash

set -e

if [[ -z "$QBT_ENV_PYTHON" ]]; then
    echo "This package requires the variable QBT_ENV_PYTHON be set to e.g. '2_7', '3_2', etc" 1>&2
    exit 1
fi

eval export PYTHON_BIN=\$PYTHON_${QBT_ENV_PYTHON}_BIN
if [[ ! -x "$PYTHON_BIN" ]]; then
    echo "This package requires the variable PYTHON_${QBT_ENV_PYTHON}_BIN be set to the path to a python binary matching that version" 1>&2
    exit 1
fi

# this qbt-make will create a virtualenv using the provided python, then install
# all our strong dependencies into it, and include it as an artifact.
# as such, you should be able to run scripts using runArtifact against this
# package.

VE=$OUTPUT_ARTIFACTS_DIR

$PYTHON_BIN -m virtualenv $VE

source $VE/bin/activate

# install wheel first if present
if [[ -f $INPUT_ARTIFACTS_DIR/weak/pypi.wheel/strong/pypi.wheel/python-src/wheel.tar.gz ]]; then
    pip install $INPUT_ARTIFACTS_DIR/weak/pypi.wheel/strong/pypi.wheel/python-src/wheel.tar.gz
fi

# install all strong python dependencies
for type in src egg whl; do
    ext=$type
    if [[ "$ext" == "src" ]]; then
        ext="tar.gz"
    fi
    for file in $INPUT_ARTIFACTS_DIR/strong/*/python-$type/*.$ext; do
        if [[ -f $file ]]; then
            pip install $file
        fi
    done
done

